# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-mmorpg-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
         version: v0.7.0

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrvtg2qpsec2kju.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4895fead2f304bc9bcdea1eb11430185 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a6db13f42aad4670a9cee81c13b48ca0 }}

    - name: Change directory to server
      run: | 
        cd server
        ls -l
        mvn clean package
        ls -l

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrvtg2qpsec2kju.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4895fead2f304bc9bcdea1eb11430185 }}/myflyff:${{ github.sha }}
        file: ./Dockerfile
        context: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-mmorpg-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_65b3a5c725cb4e698437b1f3ea50a394 }}
        images: 'acrvtg2qpsec2kju.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4895fead2f304bc9bcdea1eb11430185 }}/myflyff:${{ github.sha }}'
